#!/bin/sh

set -e

lb config noauto \
    --mode debian \
    --architectures amd64 \
    --distribution stretch \
    --linux-packages "linux-image" \
    --debian-installer false \
    --firmware-chroot true \
    --firmware-binary true \
    --archive-areas "main contrib non-free" \
    --iso-application "CUDA_LIVE" \
    --iso-publisher "yanicky" \
    --iso-volume "CUDA LIVE" \
    --parent-archive-areas "main contrib non-free" \
    --parent-mirror-bootstrap "http://deb.debian.org/debian" \
    --parent-mirror-binary "http://deb.debian.org/debian" \
    --mirror-chroot "http://deb.debian.org/debian" \
    --mirror-bootstrap "http://deb.debian.org/debian" \
    --mirror-debian-installer "http://deb.debian.org/debian" \
    --mirror-binary "http://deb.debian.org/debian" \
    --apt-indices false \
    --bootappend-live "boot=live components modprobe.blacklist=nouveau" \
    "${@}"
